---
title: "Genre Predictions"
author: "Scott Shepard"
subtitle: "Trees, Random Forest, and Multinomial Logit"
date: "8/12/2018"
output: pdf_document
---

```{r libraries}
library(dplyr)
library(ggplot2)
library(stringr)
library(reshape2)
library(rpart)
library(MASS)
```

```{r read_data}
# Read Data
special_read_csv <- function(file_path, n_rows=-1, offset=0) {
  # The flat files in this project are formatted for easy python loading. 
  # The headers are a multilevel index. 
  # The first row is the category: track, album, artist, or set. 
  # The second row is the column name: id, producer, name, etc
  # Togther they make up the full column name. These need to be read in 
  # separately and manually pasted together to get the full column names.
  row0 <- read.csv(file_path, nrows=1, skip=0+offset)
  row1 <- read.csv(file_path, nrows=1, skip=1+offset)
  
  df <- read.csv(file_path, nrows=n_rows, skip=2+offset)
  headers <- paste(
    str_replace_all(names(row0), c("\\."="", "[0-9]+"="")), 
    str_replace_all(names(row1), c("\\."="_")), 
    sep="_")
  headers[1] <- "track_id"
  names(df) <- headers
  df
}

# tracks <- special_read_csv(file.path(path, "tracks.csv"))
# echonest <- special_read_csv(file.path(path, "echonest.csv"), offset=1)[,1:26]
# df <- dplyr::inner_join(tracks, echonest, "track_id")
```

```{r clean_data}
path <- "~/Dropbox/MScA/31008 - Data Mining/Project/"
df <- read.csv(file.path(path, "Project_Data.csv"))

names(df)[names(df) == "genre_top"] <- "genre"
df$genre <- as.character(df$genre)
df$genre <- factor(df$genre)

df$tempo_scaled <- scales::rescale(df$tempo)
```

```{r exploration}
df <- df[! df$genre %in% c(""),]

ggplot(df, aes(x=genre)) + 
  geom_bar(stat='count') +
  ggthemes::theme_fivethirtyeight() +
  theme(axis.text.x = element_text(angle=90),
        axis.title.x = element_blank()) + 
  labs(title="Frequency of Genres")
  
table(df$genre)
```

```{r}
df$genre <- as.character(df$genre)
df <- df[! df$genre %in% c("", "International", "Experimental"), ]
df[df$genre %in% c("Folk", "Blues"), ]$genre <- c("Folk/Blues")
df$genre <- factor(df$genre)

ggplot(df, aes(x=genre)) + 
  geom_bar(stat='count') +
  ggthemes::theme_fivethirtyeight() +
  theme(axis.text.x = element_text(angle=90),
        axis.title.x = element_blank()) + 
  labs(title="Frequency of Genres")
  
table(df$genre)
```

```{r}
splitData <- function(data, smp_size) {
  # Take a dataset and split it randomly into train and test sets
  # The size of the training set is the smp_size argument
  train_ind <- sample(seq_len(nrow(data)), size = smp_size)
  train <- data[ train_ind, ]
  test  <- data[-train_ind, ]
  
  list("train"=train, "test"=test)
}
```

```{r}
audio_feature_cols = c("acousticness", "danceability", "energy", 
                       "instrumentalness", "liveness", "speechiness", 
                       "tempo_scaled", "valence")

melted <- melt(df, id.vars=c("genre", "track_id"),
               measure.vars=audio_feature_cols,
               variable.name="audio_feature")
melted$audio_feature <- str_remove(melted$audio_feature, "audio_features_")
```

```{r}
ggplot(df, aes(x=danceability)) + 
  geom_histogram(fill="#1db954", color="black") + 
  ggthemes::theme_fivethirtyeight() + 
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(title="Dancibility!")

ggplot(df, aes(x=acousticness)) + 
  geom_histogram(fill="#1db954", color="black") + 
  ggthemes::theme_fivethirtyeight() + 
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(title="Acousticness")
```

```{r}
ggplot(melted, aes(x=value)) + 
  geom_density(aes(y=..scaled..)) + 
  facet_grid(genre~audio_feature) + 
  labs(title="Density of Each Audio Feature with Genre")
```

Split the data

```{r data_holdout}
set.seed(1)
l <- splitData(df, round(nrow(df) * 0.7))
train <- l$train
holdout <- l$test
```

## Simple Classification Tree

```{r trees}
x = rpart(genre ~ acousticness + danceability + energy + instrumentalness + 
            liveness + speechiness + tempo + valence,
          data=train, control=rpart.control(cp=0, minsplit=10, xval=10))

plotcp(x)
printcp(x)
CP <- x$cptable[x$cptable[,'xerror'] == min(x$cptable[,'xerror']), 'CP']
CP
```

Final Model

```{r}
Simple.Tree = rpart(genre ~ acousticness + danceability + energy + 
                      instrumentalness + liveness + speechiness + tempo + valence,
                    data=train, control=rpart.control(cp=9.6360e-04, minsplit=25, xval=20, maxsurrogate=0))

train$Genre.Tree <- predict(Simple.Tree, type="class")
prop.table(table(train$genre, train$Genre.Tree))
```

Model Validation

```{r}
accuracyTable <- function(df, pred.col) {
  dots <- list(
    lazyeval::interp(~ mean(var == genre), var=as.name(pred.col)),
    ~n())
  group_by_(df, pred.col) %>%
    summarize_(.dots=setNames(dots, c("pct", "n")))
}

correctClassifyTable <- function(df, pred.col) {
  dots <- list(
    lazyeval::interp(~ mean(var == genre), var=as.name(pred.col)),
    ~n())
  group_by(df, genre) %>%
    summarize_(.dots=setNames(dots, c("pct", "n")))
}

accuracyPlot <- function(df, pred.col) {
  accuracy <- accuracyTable(df, pred.col=pred.col)
  
  ggplot(accuracy, aes_string(x=pred.col, y="pct")) + 
    geom_bar(stat="identity", fill="blue4") + 
    geom_text(aes(y=pct, label=paste0(round(pct*100,1), "%")),
              vjust=1.5, color="white") +
    geom_text(aes(y=0, label=paste0("N=",n)),
              vjust=-0.5, color="white") +
    scale_y_continuous(labels=scales::percent, 
                       limits = c(0,1)) +
    
    ggthemes::theme_fivethirtyeight() +
    theme(axis.title.x = element_blank()) +
    labs(title="Preciction Accuracy",
         subtitle="Given a Prection, How Likely is it to be true?",
         y="Percent of Values Predicted Correctly")
}

correctClassifyPlot <- function(df, pred.col) {
  correct_classify <- correctClassifyTable(df, pred.col=pred.col)
  
  ggplot(correct_classify, aes(x=genre, y=pct)) + 
    geom_bar(stat="identity", fill="blue4") + 
    geom_text(aes(y=pct, label=paste0(round(pct*100,1), "%")),
              vjust=1.5, color="white") +
    scale_y_continuous(labels=scales::percent,limits = c(0,1)) +
    ggthemes::theme_fivethirtyeight() +
    theme(axis.title.x = element_blank()) +
    labs(title="Correct Classification",
         subtitle="Given a track, how likely is it to be correctly classified?",
         y="Percent of Observations Correctly Classified")
}

accuracyPlot(train, "Genre.Tree")
correctClassifyPlot(train, "Genre.Tree")
```

Holdout validation

```{r}
holdout$Genre.Tree <- predict(Simple.Tree, type="class", newdata = holdout)

table(holdout$genre, holdout$Genre.Tree)

accuracyPlot(holdout, "Genre.Tree")
```

# Multinomial Logit

```{r}
Multi.Logit <- nnet::multinom(genre ~ acousticness + danceability + energy + 
                      instrumentalness + liveness + speechiness + tempo +
                        valence,
                    data=train)

train$Genre.Multilogit <- predict(Multi.Logit, data=train)
table(train$genre, train$Genre.Multilogit)

accuracyPlot(train, "Genre.Multilogit")

holdout$Genre.Multilogit <- predict(Multi.Logit, newdata=holdout)

accuracyPlot(holdout, "Genre.Multilogit") + ggtitle("Accuracy of Multi Logistic")

mean(holdout$Genre.Multilogit == holdout$genre)
```

# LDA & QDA

```{r}
LDA.Model <- MASS::lda(genre ~ . ,train[,c('genre','acousticness','danceability',
                                      'energy','instrumentalness','liveness',
                                      'speechiness','tempo','valence')])
train$Genre.LDA <- predict(LDA.Model)$class

QDA.Model <- MASS::qda(genre ~ . ,train[,c('genre','acousticness','danceability',
                                      'energy','instrumentalness','liveness',
                                      'speechiness','tempo','valence')])

train$Genre.QDA <- predict(QDA.Model)$class

accuracyPlot(train, "Genre.LDA")
correctClassifyPlot(train, "Genre.LDA")

accuracyPlot(train, "Genre.QDA") 
correctClassifyPlot(train, "Genre.QDA")
```

```{r}
path <- "~/Dropbox/MScA/31008 - Data Mining/Project/plots"

holdout$Genre.LDA <- predict(LDA.Model, newdata=holdout)$class
holdout$Genre.QDA <- predict(QDA.Model, newdata=holdout)$class

accuracyPlot(holdout, "Genre.LDA") + ggtitle("Accuracy of LDA in Holdout")
accuracyPlot(holdout, "Genre.QDA") + ggtitle("Accuracy of QDA")
```

```{r}
Model.RF <- randomForest::randomForest(genre ~ acousticness + danceability + energy + 
                      instrumentalness + liveness + speechiness + tempo + valence, 
                      data=train)
train$Genre.RF <- Model.RF$predicted
holdout$Genre.RF <- predict(Model.RF, newdata = holdout)
```

```{r}
accuracyPlot(holdout, "Genre.RF") + ggtitle("Accuracy of Random Forest in Holdout")
correctClassifyPlot(holdout, "Genre.RF")
```

```{r}

accuracyPlot(train, "Genre.RF")
correctClassifyPlot(train, "Genre.RF")

accuracyPlot(train, "Genre.Tree")
correctClassifyPlot(train, "Genre.Tree")

accuracyPlot(holdout, "Genre.RF")
correctClassifyPlot(holdout, "Genre.RF")

accuracyPlot(holdout, "Genre.Tree")
correctClassifyPlot(holdout, "Genre.Tree")
```

```{r}
accuracyPlot(holdout, "Genre.Multilogit") + ggtitle("Accuracy of Multi Logistic")
accuracyPlot(holdout, "Genre.LDA") + ggtitle("Accuracy of LDA")
accuracyPlot(holdout, "Genre.RF") + ggtitle("Accuracy of Random Forest")
```
